[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
dynamic_test_linking = true

# Remappings for OpenZeppelin contracts
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

# Fuzz testing configuration
[fuzz]
runs = 1000
max_test_rejects = 65536

# Invariant testing configuration
[invariant]
runs = 256
depth = 15
fail_on_revert = false
show_metrics = true

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
