[profile.default]
solc-version = '0.8.22'
src = 'contracts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
verbosity = 3
optimize = true
optimizer_runs = 1000
libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    # 
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to our own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

[fuzz]
runs = 1000

# Network configurations for LayerZero testnet deployment
[rpc_endpoints]
optimism-sepolia = "${RPC_URL_OP_SEPOLIA}"
avalanche-fuji = "${RPC_URL_FUJI}"
arbitrum-sepolia = "${RPC_URL_ARB_SEPOLIA}"

[etherscan]
optimism-sepolia = { key = "${ETHERSCAN_API_KEY_OPTIMISM}", url = "https://api-sepolia-optimism.etherscan.io/api" }
avalanche-fuji = { key = "${ETHERSCAN_API_KEY_AVALANCHE}", url = "https://api-testnet.snowtrace.io/api" }
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "https://api-sepolia.arbiscan.io/api" }
